// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: players.proto

package generated_code;

public final class Players {
  private Players() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SuggestionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Suggestion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 suggestion_id = 1;</code>
     */
    int getSuggestionId();

    /**
     * <code>int32 player_id = 2;</code>
     */
    int getPlayerId();

    /**
     * <code>string weapon = 3;</code>
     */
    java.lang.String getWeapon();
    /**
     * <code>string weapon = 3;</code>
     */
    com.google.protobuf.ByteString
        getWeaponBytes();

    /**
     * <code>.RoomInfo room = 4;</code>
     */
    boolean hasRoom();
    /**
     * <code>.RoomInfo room = 4;</code>
     */
    generated_code.Players.RoomInfo getRoom();
    /**
     * <code>.RoomInfo room = 4;</code>
     */
    generated_code.Players.RoomInfoOrBuilder getRoomOrBuilder();

    /**
     * <code>bool is_accusation = 5;</code>
     */
    boolean getIsAccusation();
  }
  /**
   * Protobuf type {@code Suggestion}
   */
  public  static final class Suggestion extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Suggestion)
      SuggestionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Suggestion.newBuilder() to construct.
    private Suggestion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Suggestion() {
      suggestionId_ = 0;
      playerId_ = 0;
      weapon_ = "";
      isAccusation_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Suggestion(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              suggestionId_ = input.readInt32();
              break;
            }
            case 16: {

              playerId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              weapon_ = s;
              break;
            }
            case 34: {
              generated_code.Players.RoomInfo.Builder subBuilder = null;
              if (room_ != null) {
                subBuilder = room_.toBuilder();
              }
              room_ = input.readMessage(generated_code.Players.RoomInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(room_);
                room_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {

              isAccusation_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generated_code.Players.internal_static_Suggestion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generated_code.Players.internal_static_Suggestion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generated_code.Players.Suggestion.class, generated_code.Players.Suggestion.Builder.class);
    }

    public static final int SUGGESTION_ID_FIELD_NUMBER = 1;
    private int suggestionId_;
    /**
     * <code>int32 suggestion_id = 1;</code>
     */
    public int getSuggestionId() {
      return suggestionId_;
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 2;
    private int playerId_;
    /**
     * <code>int32 player_id = 2;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int WEAPON_FIELD_NUMBER = 3;
    private volatile java.lang.Object weapon_;
    /**
     * <code>string weapon = 3;</code>
     */
    public java.lang.String getWeapon() {
      java.lang.Object ref = weapon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weapon_ = s;
        return s;
      }
    }
    /**
     * <code>string weapon = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWeaponBytes() {
      java.lang.Object ref = weapon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weapon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOM_FIELD_NUMBER = 4;
    private generated_code.Players.RoomInfo room_;
    /**
     * <code>.RoomInfo room = 4;</code>
     */
    public boolean hasRoom() {
      return room_ != null;
    }
    /**
     * <code>.RoomInfo room = 4;</code>
     */
    public generated_code.Players.RoomInfo getRoom() {
      return room_ == null ? generated_code.Players.RoomInfo.getDefaultInstance() : room_;
    }
    /**
     * <code>.RoomInfo room = 4;</code>
     */
    public generated_code.Players.RoomInfoOrBuilder getRoomOrBuilder() {
      return getRoom();
    }

    public static final int IS_ACCUSATION_FIELD_NUMBER = 5;
    private boolean isAccusation_;
    /**
     * <code>bool is_accusation = 5;</code>
     */
    public boolean getIsAccusation() {
      return isAccusation_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (suggestionId_ != 0) {
        output.writeInt32(1, suggestionId_);
      }
      if (playerId_ != 0) {
        output.writeInt32(2, playerId_);
      }
      if (!getWeaponBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, weapon_);
      }
      if (room_ != null) {
        output.writeMessage(4, getRoom());
      }
      if (isAccusation_ != false) {
        output.writeBool(5, isAccusation_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (suggestionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, suggestionId_);
      }
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      if (!getWeaponBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, weapon_);
      }
      if (room_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getRoom());
      }
      if (isAccusation_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isAccusation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generated_code.Players.Suggestion)) {
        return super.equals(obj);
      }
      generated_code.Players.Suggestion other = (generated_code.Players.Suggestion) obj;

      boolean result = true;
      result = result && (getSuggestionId()
          == other.getSuggestionId());
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && getWeapon()
          .equals(other.getWeapon());
      result = result && (hasRoom() == other.hasRoom());
      if (hasRoom()) {
        result = result && getRoom()
            .equals(other.getRoom());
      }
      result = result && (getIsAccusation()
          == other.getIsAccusation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUGGESTION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSuggestionId();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId();
      hash = (37 * hash) + WEAPON_FIELD_NUMBER;
      hash = (53 * hash) + getWeapon().hashCode();
      if (hasRoom()) {
        hash = (37 * hash) + ROOM_FIELD_NUMBER;
        hash = (53 * hash) + getRoom().hashCode();
      }
      hash = (37 * hash) + IS_ACCUSATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAccusation());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generated_code.Players.Suggestion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.Suggestion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.Suggestion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.Suggestion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.Suggestion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.Suggestion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.Suggestion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.Suggestion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.Suggestion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static generated_code.Players.Suggestion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.Suggestion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.Suggestion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generated_code.Players.Suggestion prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Suggestion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Suggestion)
        generated_code.Players.SuggestionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generated_code.Players.internal_static_Suggestion_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generated_code.Players.internal_static_Suggestion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generated_code.Players.Suggestion.class, generated_code.Players.Suggestion.Builder.class);
      }

      // Construct using generated_code.Players.Suggestion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        suggestionId_ = 0;

        playerId_ = 0;

        weapon_ = "";

        if (roomBuilder_ == null) {
          room_ = null;
        } else {
          room_ = null;
          roomBuilder_ = null;
        }
        isAccusation_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generated_code.Players.internal_static_Suggestion_descriptor;
      }

      @java.lang.Override
      public generated_code.Players.Suggestion getDefaultInstanceForType() {
        return generated_code.Players.Suggestion.getDefaultInstance();
      }

      @java.lang.Override
      public generated_code.Players.Suggestion build() {
        generated_code.Players.Suggestion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generated_code.Players.Suggestion buildPartial() {
        generated_code.Players.Suggestion result = new generated_code.Players.Suggestion(this);
        result.suggestionId_ = suggestionId_;
        result.playerId_ = playerId_;
        result.weapon_ = weapon_;
        if (roomBuilder_ == null) {
          result.room_ = room_;
        } else {
          result.room_ = roomBuilder_.build();
        }
        result.isAccusation_ = isAccusation_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generated_code.Players.Suggestion) {
          return mergeFrom((generated_code.Players.Suggestion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generated_code.Players.Suggestion other) {
        if (other == generated_code.Players.Suggestion.getDefaultInstance()) return this;
        if (other.getSuggestionId() != 0) {
          setSuggestionId(other.getSuggestionId());
        }
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        if (!other.getWeapon().isEmpty()) {
          weapon_ = other.weapon_;
          onChanged();
        }
        if (other.hasRoom()) {
          mergeRoom(other.getRoom());
        }
        if (other.getIsAccusation() != false) {
          setIsAccusation(other.getIsAccusation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generated_code.Players.Suggestion parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generated_code.Players.Suggestion) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int suggestionId_ ;
      /**
       * <code>int32 suggestion_id = 1;</code>
       */
      public int getSuggestionId() {
        return suggestionId_;
      }
      /**
       * <code>int32 suggestion_id = 1;</code>
       */
      public Builder setSuggestionId(int value) {
        
        suggestionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 suggestion_id = 1;</code>
       */
      public Builder clearSuggestionId() {
        
        suggestionId_ = 0;
        onChanged();
        return this;
      }

      private int playerId_ ;
      /**
       * <code>int32 player_id = 2;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int32 player_id = 2;</code>
       */
      public Builder setPlayerId(int value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player_id = 2;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object weapon_ = "";
      /**
       * <code>string weapon = 3;</code>
       */
      public java.lang.String getWeapon() {
        java.lang.Object ref = weapon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weapon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string weapon = 3;</code>
       */
      public com.google.protobuf.ByteString
          getWeaponBytes() {
        java.lang.Object ref = weapon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weapon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string weapon = 3;</code>
       */
      public Builder setWeapon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weapon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string weapon = 3;</code>
       */
      public Builder clearWeapon() {
        
        weapon_ = getDefaultInstance().getWeapon();
        onChanged();
        return this;
      }
      /**
       * <code>string weapon = 3;</code>
       */
      public Builder setWeaponBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weapon_ = value;
        onChanged();
        return this;
      }

      private generated_code.Players.RoomInfo room_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          generated_code.Players.RoomInfo, generated_code.Players.RoomInfo.Builder, generated_code.Players.RoomInfoOrBuilder> roomBuilder_;
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public boolean hasRoom() {
        return roomBuilder_ != null || room_ != null;
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public generated_code.Players.RoomInfo getRoom() {
        if (roomBuilder_ == null) {
          return room_ == null ? generated_code.Players.RoomInfo.getDefaultInstance() : room_;
        } else {
          return roomBuilder_.getMessage();
        }
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public Builder setRoom(generated_code.Players.RoomInfo value) {
        if (roomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          room_ = value;
          onChanged();
        } else {
          roomBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public Builder setRoom(
          generated_code.Players.RoomInfo.Builder builderForValue) {
        if (roomBuilder_ == null) {
          room_ = builderForValue.build();
          onChanged();
        } else {
          roomBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public Builder mergeRoom(generated_code.Players.RoomInfo value) {
        if (roomBuilder_ == null) {
          if (room_ != null) {
            room_ =
              generated_code.Players.RoomInfo.newBuilder(room_).mergeFrom(value).buildPartial();
          } else {
            room_ = value;
          }
          onChanged();
        } else {
          roomBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public Builder clearRoom() {
        if (roomBuilder_ == null) {
          room_ = null;
          onChanged();
        } else {
          room_ = null;
          roomBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public generated_code.Players.RoomInfo.Builder getRoomBuilder() {
        
        onChanged();
        return getRoomFieldBuilder().getBuilder();
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      public generated_code.Players.RoomInfoOrBuilder getRoomOrBuilder() {
        if (roomBuilder_ != null) {
          return roomBuilder_.getMessageOrBuilder();
        } else {
          return room_ == null ?
              generated_code.Players.RoomInfo.getDefaultInstance() : room_;
        }
      }
      /**
       * <code>.RoomInfo room = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          generated_code.Players.RoomInfo, generated_code.Players.RoomInfo.Builder, generated_code.Players.RoomInfoOrBuilder> 
          getRoomFieldBuilder() {
        if (roomBuilder_ == null) {
          roomBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              generated_code.Players.RoomInfo, generated_code.Players.RoomInfo.Builder, generated_code.Players.RoomInfoOrBuilder>(
                  getRoom(),
                  getParentForChildren(),
                  isClean());
          room_ = null;
        }
        return roomBuilder_;
      }

      private boolean isAccusation_ ;
      /**
       * <code>bool is_accusation = 5;</code>
       */
      public boolean getIsAccusation() {
        return isAccusation_;
      }
      /**
       * <code>bool is_accusation = 5;</code>
       */
      public Builder setIsAccusation(boolean value) {
        
        isAccusation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_accusation = 5;</code>
       */
      public Builder clearIsAccusation() {
        
        isAccusation_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Suggestion)
    }

    // @@protoc_insertion_point(class_scope:Suggestion)
    private static final generated_code.Players.Suggestion DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generated_code.Players.Suggestion();
    }

    public static generated_code.Players.Suggestion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Suggestion>
        PARSER = new com.google.protobuf.AbstractParser<Suggestion>() {
      @java.lang.Override
      public Suggestion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Suggestion(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Suggestion> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Suggestion> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generated_code.Players.Suggestion getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoomInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoomInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 room_id = 1;</code>
     */
    int getRoomId();

    /**
     * <code>string room_name = 2;</code>
     */
    java.lang.String getRoomName();
    /**
     * <code>string room_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getRoomNameBytes();
  }
  /**
   * Protobuf type {@code RoomInfo}
   */
  public  static final class RoomInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoomInfo)
      RoomInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomInfo.newBuilder() to construct.
    private RoomInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomInfo() {
      roomId_ = 0;
      roomName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              roomId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              roomName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generated_code.Players.internal_static_RoomInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generated_code.Players.internal_static_RoomInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generated_code.Players.RoomInfo.class, generated_code.Players.RoomInfo.Builder.class);
    }

    public static final int ROOM_ID_FIELD_NUMBER = 1;
    private int roomId_;
    /**
     * <code>int32 room_id = 1;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    public static final int ROOM_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object roomName_;
    /**
     * <code>string room_name = 2;</code>
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      }
    }
    /**
     * <code>string room_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roomId_ != 0) {
        output.writeInt32(1, roomId_);
      }
      if (!getRoomNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roomId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomId_);
      }
      if (!getRoomNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generated_code.Players.RoomInfo)) {
        return super.equals(obj);
      }
      generated_code.Players.RoomInfo other = (generated_code.Players.RoomInfo) obj;

      boolean result = true;
      result = result && (getRoomId()
          == other.getRoomId());
      result = result && getRoomName()
          .equals(other.getRoomName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId();
      hash = (37 * hash) + ROOM_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRoomName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generated_code.Players.RoomInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.RoomInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.RoomInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.RoomInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.RoomInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.RoomInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.RoomInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.RoomInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.RoomInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static generated_code.Players.RoomInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.RoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.RoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generated_code.Players.RoomInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoomInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoomInfo)
        generated_code.Players.RoomInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generated_code.Players.internal_static_RoomInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generated_code.Players.internal_static_RoomInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generated_code.Players.RoomInfo.class, generated_code.Players.RoomInfo.Builder.class);
      }

      // Construct using generated_code.Players.RoomInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomId_ = 0;

        roomName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generated_code.Players.internal_static_RoomInfo_descriptor;
      }

      @java.lang.Override
      public generated_code.Players.RoomInfo getDefaultInstanceForType() {
        return generated_code.Players.RoomInfo.getDefaultInstance();
      }

      @java.lang.Override
      public generated_code.Players.RoomInfo build() {
        generated_code.Players.RoomInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generated_code.Players.RoomInfo buildPartial() {
        generated_code.Players.RoomInfo result = new generated_code.Players.RoomInfo(this);
        result.roomId_ = roomId_;
        result.roomName_ = roomName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generated_code.Players.RoomInfo) {
          return mergeFrom((generated_code.Players.RoomInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generated_code.Players.RoomInfo other) {
        if (other == generated_code.Players.RoomInfo.getDefaultInstance()) return this;
        if (other.getRoomId() != 0) {
          setRoomId(other.getRoomId());
        }
        if (!other.getRoomName().isEmpty()) {
          roomName_ = other.roomName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generated_code.Players.RoomInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generated_code.Players.RoomInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int roomId_ ;
      /**
       * <code>int32 room_id = 1;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>int32 room_id = 1;</code>
       */
      public Builder setRoomId(int value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 room_id = 1;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object roomName_ = "";
      /**
       * <code>string room_name = 2;</code>
       */
      public java.lang.String getRoomName() {
        java.lang.Object ref = roomName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string room_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        java.lang.Object ref = roomName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string room_name = 2;</code>
       */
      public Builder setRoomName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string room_name = 2;</code>
       */
      public Builder clearRoomName() {
        
        roomName_ = getDefaultInstance().getRoomName();
        onChanged();
        return this;
      }
      /**
       * <code>string room_name = 2;</code>
       */
      public Builder setRoomNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RoomInfo)
    }

    // @@protoc_insertion_point(class_scope:RoomInfo)
    private static final generated_code.Players.RoomInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generated_code.Players.RoomInfo();
    }

    public static generated_code.Players.RoomInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomInfo>
        PARSER = new com.google.protobuf.AbstractParser<RoomInfo>() {
      @java.lang.Override
      public RoomInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generated_code.Players.RoomInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 player_id = 1;</code>
     */
    int getPlayerId();
  }
  /**
   * Protobuf type {@code PlayerID}
   */
  public  static final class PlayerID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerID)
      PlayerIDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerID.newBuilder() to construct.
    private PlayerID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerID() {
      playerId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              playerId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generated_code.Players.internal_static_PlayerID_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generated_code.Players.internal_static_PlayerID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generated_code.Players.PlayerID.class, generated_code.Players.PlayerID.Builder.class);
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>int32 player_id = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0) {
        output.writeInt32(1, playerId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generated_code.Players.PlayerID)) {
        return super.equals(obj);
      }
      generated_code.Players.PlayerID other = (generated_code.Players.PlayerID) obj;

      boolean result = true;
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generated_code.Players.PlayerID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.PlayerID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.PlayerID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.PlayerID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.PlayerID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.PlayerID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.PlayerID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.PlayerID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.PlayerID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static generated_code.Players.PlayerID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.PlayerID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.PlayerID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generated_code.Players.PlayerID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerID)
        generated_code.Players.PlayerIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generated_code.Players.internal_static_PlayerID_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generated_code.Players.internal_static_PlayerID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generated_code.Players.PlayerID.class, generated_code.Players.PlayerID.Builder.class);
      }

      // Construct using generated_code.Players.PlayerID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generated_code.Players.internal_static_PlayerID_descriptor;
      }

      @java.lang.Override
      public generated_code.Players.PlayerID getDefaultInstanceForType() {
        return generated_code.Players.PlayerID.getDefaultInstance();
      }

      @java.lang.Override
      public generated_code.Players.PlayerID build() {
        generated_code.Players.PlayerID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generated_code.Players.PlayerID buildPartial() {
        generated_code.Players.PlayerID result = new generated_code.Players.PlayerID(this);
        result.playerId_ = playerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generated_code.Players.PlayerID) {
          return mergeFrom((generated_code.Players.PlayerID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generated_code.Players.PlayerID other) {
        if (other == generated_code.Players.PlayerID.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generated_code.Players.PlayerID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generated_code.Players.PlayerID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerId_ ;
      /**
       * <code>int32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int32 player_id = 1;</code>
       */
      public Builder setPlayerId(int value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerID)
    }

    // @@protoc_insertion_point(class_scope:PlayerID)
    private static final generated_code.Players.PlayerID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generated_code.Players.PlayerID();
    }

    public static generated_code.Players.PlayerID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerID>
        PARSER = new com.google.protobuf.AbstractParser<PlayerID>() {
      @java.lang.Override
      public PlayerID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerID> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generated_code.Players.PlayerID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfirmationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Confirmation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 conf_code = 1;</code>
     */
    int getConfCode();
  }
  /**
   * Protobuf type {@code Confirmation}
   */
  public  static final class Confirmation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Confirmation)
      ConfirmationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Confirmation.newBuilder() to construct.
    private Confirmation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Confirmation() {
      confCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Confirmation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              confCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generated_code.Players.internal_static_Confirmation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generated_code.Players.internal_static_Confirmation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generated_code.Players.Confirmation.class, generated_code.Players.Confirmation.Builder.class);
    }

    public static final int CONF_CODE_FIELD_NUMBER = 1;
    private int confCode_;
    /**
     * <code>int32 conf_code = 1;</code>
     */
    public int getConfCode() {
      return confCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (confCode_ != 0) {
        output.writeInt32(1, confCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (confCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, confCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generated_code.Players.Confirmation)) {
        return super.equals(obj);
      }
      generated_code.Players.Confirmation other = (generated_code.Players.Confirmation) obj;

      boolean result = true;
      result = result && (getConfCode()
          == other.getConfCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONF_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getConfCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generated_code.Players.Confirmation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.Confirmation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.Confirmation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.Confirmation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.Confirmation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generated_code.Players.Confirmation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generated_code.Players.Confirmation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.Confirmation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.Confirmation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static generated_code.Players.Confirmation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generated_code.Players.Confirmation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generated_code.Players.Confirmation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generated_code.Players.Confirmation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Confirmation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Confirmation)
        generated_code.Players.ConfirmationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generated_code.Players.internal_static_Confirmation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generated_code.Players.internal_static_Confirmation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generated_code.Players.Confirmation.class, generated_code.Players.Confirmation.Builder.class);
      }

      // Construct using generated_code.Players.Confirmation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        confCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generated_code.Players.internal_static_Confirmation_descriptor;
      }

      @java.lang.Override
      public generated_code.Players.Confirmation getDefaultInstanceForType() {
        return generated_code.Players.Confirmation.getDefaultInstance();
      }

      @java.lang.Override
      public generated_code.Players.Confirmation build() {
        generated_code.Players.Confirmation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generated_code.Players.Confirmation buildPartial() {
        generated_code.Players.Confirmation result = new generated_code.Players.Confirmation(this);
        result.confCode_ = confCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generated_code.Players.Confirmation) {
          return mergeFrom((generated_code.Players.Confirmation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generated_code.Players.Confirmation other) {
        if (other == generated_code.Players.Confirmation.getDefaultInstance()) return this;
        if (other.getConfCode() != 0) {
          setConfCode(other.getConfCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generated_code.Players.Confirmation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generated_code.Players.Confirmation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int confCode_ ;
      /**
       * <code>int32 conf_code = 1;</code>
       */
      public int getConfCode() {
        return confCode_;
      }
      /**
       * <code>int32 conf_code = 1;</code>
       */
      public Builder setConfCode(int value) {
        
        confCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 conf_code = 1;</code>
       */
      public Builder clearConfCode() {
        
        confCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Confirmation)
    }

    // @@protoc_insertion_point(class_scope:Confirmation)
    private static final generated_code.Players.Confirmation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generated_code.Players.Confirmation();
    }

    public static generated_code.Players.Confirmation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Confirmation>
        PARSER = new com.google.protobuf.AbstractParser<Confirmation>() {
      @java.lang.Override
      public Confirmation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Confirmation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Confirmation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Confirmation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generated_code.Players.Confirmation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Suggestion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Suggestion_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerID_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Confirmation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Confirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rplayers.proto\"v\n\nSuggestion\022\025\n\rsuggest" +
      "ion_id\030\001 \001(\005\022\021\n\tplayer_id\030\002 \001(\005\022\016\n\006weapo" +
      "n\030\003 \001(\t\022\027\n\004room\030\004 \001(\0132\t.RoomInfo\022\025\n\ris_a" +
      "ccusation\030\005 \001(\010\".\n\010RoomInfo\022\017\n\007room_id\030\001" +
      " \001(\005\022\021\n\troom_name\030\002 \001(\t\"\035\n\010PlayerID\022\021\n\tp" +
      "layer_id\030\001 \001(\005\"!\n\014Confirmation\022\021\n\tconf_c" +
      "ode\030\001 \001(\0052a\n\014GameServices\022,\n\016makeSuggest" +
      "ion\022\013.Suggestion\032\r.Confirmation\022#\n\tsubsc" +
      "ribe\022\t.PlayerID\032\013.SuggestionB\020\n\016generate" +
      "d_codeb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Suggestion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Suggestion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Suggestion_descriptor,
        new java.lang.String[] { "SuggestionId", "PlayerId", "Weapon", "Room", "IsAccusation", });
    internal_static_RoomInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomInfo_descriptor,
        new java.lang.String[] { "RoomId", "RoomName", });
    internal_static_PlayerID_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PlayerID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerID_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_Confirmation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Confirmation_descriptor,
        new java.lang.String[] { "ConfCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
